%From Harstone et al. (2021) and Chao et al. (2018)
clear trialData_detrend trialData_tempnorm trialData_ensnorm
for i_TD = 1:length(ToneDur_text)
    
    trialData_detrend{i_TD} = trialData{i_TD};
    trialData_tempnorm{i_TD} = trialData{i_TD};
    trialData_ensnorm{i_TD} = trialData{i_TD};
    
    for i_elec = 1:size(trialData{i_TD},1)
        for i_tonegroup = 1:size(param.GC.tone_aggregation,2)
            for i_trial = 1:size(trialData{i_TD},3)
                %                         figure;
                %                         hold on
                %                         plot(trialData{i_TD}...
                %                             (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                %                             Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial),'k-')
                %1) Detrend tone snippets for each electrode
                trialData_detrend{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) = ...
                    detrend(...
                    trialData{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial));
                
                %                         plot(trialData{i_TD}...
                %                             (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                %                             Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial),'b-')
                
                %                         %2) Temporal normalization, which is the subtraction of the mean of each time series and division by the standard deviation,
                %                         %ensures that all variables have equal weights across the trial. These processes were performed on each trial for each channel.
                trialData_tempnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) = ...
                    trialData_detrend{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) - ...
                    nanmean(trialData_detrend{i_TD}(i_elec,:,i_trial));
                trialData_tempnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) = ...
                    trialData_tempnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) ./ ...
                    nanstd(trialData_tempnorm{i_TD}(i_elec,:,i_trial));
                %
                % %                         plot(trialData{i_TD}...
                % %                             (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                % %                             Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial),'c-')
                %
                %3)Ensemble normalization, which is the pointwise subtraction of the ensemble mean
                %(calculated by averaging the measured amplitude values at a given channel at each
                %time point across trials) and division by the ensemble standard deviation,
                %dramatically improves the local stationarity of the data
                trialData_ensnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) = ...
                    trialData_tempnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) - ...
                    nanmean(squeeze(trialData_tempnorm{i_TD}(i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),:)),2)';
                trialData_ensnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) = ...
                    trialData_ensnorm{i_TD}...
                    (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial) ./ ...
                    nanstd(squeeze(trialData_ensnorm{i_TD}(i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                    Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),:)),0,2)';
                %
                % %                         plot(trialData{i_TD}...
                % %                             (i_elec,Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(1),1):...
                % %                             Sample_Tone_StartStop{i_TD}(param.GC.tone_aggregation{i_tonegroup}(end),2),i_trial),'m-')
                
                i_TD = 1
                
                %Mean across channels
                figure
                subplot(2,2,1)
                plot(nanmean(trialData{i_TD},3)')
                subplot(2,2,2)
                plot(nanmean(trialData_detrend{i_TD},3)')
                subplot(2,2,3)
                plot(nanmean(trialData_tempnorm{i_TD},3)')
                subplot(2,2,4)
                plot(nanmean(trialData_ensnorm{i_TD},3)')
                
                %random channel
                i_chan = 5
                
                figure
                subplot(2,2,1)
                plot(squeeze(trialData{i_TD}(i_chan,:,:)))
                subplot(2,2,2)
                plot(squeeze(trialData_detrend{i_TD}(i_chan,:,:)))
                subplot(2,2,3)
                plot(squeeze(trialData_tempnorm{i_TD}(i_chan,:,:)))
                subplot(2,2,4)
                plot(squeeze(trialData_ensnorm{i_TD}(i_chan,:,:)))
                
                figure
                subplot(2,2,1)
                imagesc(squeeze(trialData{i_TD}(i_chan,:,:))')
                colorbar
                subplot(2,2,2)
                imagesc(squeeze(trialData_detrend{i_TD}(i_chan,:,:))')
                colorbar
                subplot(2,2,3)
                imagesc(squeeze(trialData_tempnorm{i_TD}(i_chan,:,:))')
                colorbar
                subplot(2,2,4)
                imagesc(squeeze(trialData_ensnorm{i_TD}(i_chan,:,:))')
                colorbar
                
                
                
            end
        end
    end
end